apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-2
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-go-basic-2
  namespace: user-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-go-basic-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-go-basic-2
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:user-workspace-devfile-sample-go-basic-2
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
